[colors.primary]
background = "0x282828"  # Gruvbox Dark (medium)
foreground = "0xebdbb2"  # Soft light foreground

[colors.normal]
black   = "0x282828"
red     = "0xcc241d"
green   = "0x98971a"
yellow  = "0xd79921"
blue    = "0x458588"
magenta = "0xb16286"
cyan    = "0x689d6a"
white   = "0xa89984"

[colors.bright]
black   = "0x928374"
red     = "0xfb4934"
green   = "0xb8bb26"
yellow  = "0xfabd2f"
blue    = "0x83a598"
magenta = "0xd3869b"
cyan    = "0x8ec07c"
white   = "0xebdbb2"

[font]
normal.family = "MesloLGS NF"
size = 12.0

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dimensions.columns = 80
dimensions.lines = 24

[window.padding]
x = 8
y = 6

# Fullscreen is conflicting, figure out later
# [[keyboard.bindings]]
# key = "Return"
# mods = "Alt"
# action = "ToggleFullscreen"
